version: '3.9'
services:

  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    volumes:
      - ./zookeeper:/bitnami/zookeeper/data
    environment:
      - ZOO_ENABLE_AUTH=yes
  
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - 9092:9092
    volumes:
      - ./kafka:/bitnami/kafka/data
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  mysql:
    image: mysql
    container_name: ktb_kafka
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=pek
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ktb_kafka
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql